---
driver:
  name: ec2
  aws_ssh_key_id: learnchef
  region: us-west-2
  availability_zone: a
  image_id: ami-87c037e7
  subnet_id: subnet-eacb348f
  instance_type: t2.medium
  security_group_ids: ['sg-2d3b3b48']
  retryable_tries: 120
  associate_public_ip: true

provisioner:
  name: chef_zero

transport:
  name: winrm
  elevated: true
  ssh_key: C:\Users\LearnChef\.ssh\learnchef.pem

platforms:
  - name: windows-2012r2
    transport:
      username: Administrator

suites:
  - name: default
    run_list:
      - recipe[awesome_customers_windows::default]
    attributes:
      sql_server:
        server_sa_password: 'SQL_sa_pa$$w0rd'
